# Generated by Django 5.0.2 on 2025-05-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cabinet', '0003_rendezvous_montant_rendezvous_statut_paiement'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='secretaire',
            table=None,
        ),
    ]
